version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/postgres-init/
      - ./postgres-init/migrations:/postgres-init/migrations
      - ./postgres-init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
      - my_db_volume:/var/lib/postgresql/data

volumes:
  my_db_volume:

